EDC2Reporting.WebAPI/Controllers/CrfPagesController.cs
using DataServices.SqlServerRepository;
using DataServices.SqlServerRepository.Models.CrfModels;
using EDC2Reporting.WebAPI.Filters;
using EDC2Reporting.WebAPI.Models;
using EDC2Reporting.WebAPI.Models.Managers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EDC2Reporting.WebAPI.Controllers
{
    public class CrfPagesController : Controller
    {
        private readonly ICrfPageManager _manager;
        private readonly EdcDbContext _db;

        public CrfPagesController(EdcDbContext db)
        {
            _manager = new CrfPageManager(db);
            _db = db;
        }

        // GET: CrfPages
        public async Task<IActionResult> Index()
        {
            var pages = await _manager.GetAllAsync();
            return View(pages);
        }

        // GET: CrfPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var page = await _manager.GetByIdAsync(id.Value);
            if (page == null) return NotFound();

            return View(page);
        }

        // GET: CrfPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CrfPages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudyId,Name,Html,Description,IsLockedForChanges,GuidId,IsDeleted")] CrfPage page)
        {
            if (ModelState.IsValid)
            {
                await _manager.CreateAsync(page);
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: CrfPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var page = await _manager.GetByIdAsync(id.Value);
            if (page == null) return NotFound();

            return View(page);
        }

        // POST: CrfPages/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudyId,Name,Html,Description,IsLockedForChanges,GuidId,IsDeleted")] CrfPage page)
        {
            if (id != page.Id) return NotFound();

            if (ModelState.IsValid)
            {
                var updated = await _manager.UpdateAsync(page);
                if (!updated) return NotFound();

                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: CrfPages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var page = await _manager.GetByIdAsync(id.Value);
            if (page == null) return NotFound();

            return View(page);
        }

        // POST: CrfPages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _manager.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        // NEW: GET: CrfPages/GetFromExternal/5
        public async Task<IActionResult> GetFromExternal(int id)
        {
            if (id <= 0) return BadRequest("Invalid remote id.");

            var importer = new CrfImporter(_db);
            var baseUrl = "https://www.crfdesign.somee.com/RenderCrfComponent/Index";

            string html;
            try
            {
                html = await importer.GetHtmlFromRemote(baseUrl, id);
            }
            catch (Exception ex)
            {
                // In production consider logging the exception with ILogger
                return BadRequest($"Failed to fetch remote HTML: {ex.Message}");
            }

            var newPage = importer.ParseNewCrfPage(html);
            if (newPage == null) return BadRequest("Failed to parse remote CRF HTML.");

            await importer.SaveAsyncToDb(newPage);

            return RedirectToAction(nameof(Index));
        }

    }
}

EDC2Reporting.WebAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using EDC2Reporting.WebAPI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace EDC2Reporting.WebAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [ResponseCache(Duration=1000, Location = ResponseCacheLocation.Any)]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult DesignExperiment()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AdminOnly()
        {
            return View();
        }
    }
}

EDC2Reporting.WebAPI/Controllers/SiteController.cs
using DataServices.Interfaces;
using DataServices.Providers;
using DataServices.SqlServerRepository.Models;
using MainStaticMaintainableEntities.SiteAssembly;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.Linq;
using ActionResult = Microsoft.AspNetCore.Mvc.ActionResult;

namespace EDC2Reporting.WebAPI.Controllers
{
    public class SiteController : Controller
    {
        private readonly ILogger<SiteController> _logger;
        private IRepository<Site> repository;
        private IRepository<Country> countryRepository;
        private IRepository<City> cityRepository;
        private readonly RepositoryOptions repoOptions;

        public SiteController(ILogger<SiteController> logger, IOptionsSnapshot<RepositoryOptions> options)
        {
            _logger = logger;
            repoOptions = options.Value;
            RepositoryLocator<Country> country_repositoryLocator = new RepositoryLocator<Country>();
            countryRepository = country_repositoryLocator.GetRepository(repoOptions.RepositoryType);
            RepositoryLocator<City> city_repositoryLocator = new RepositoryLocator<City>();
            cityRepository = city_repositoryLocator.GetRepository(repoOptions.RepositoryType);
            RepositoryLocator<Site> repositoryLocator = new RepositoryLocator<Site>();
            repository = repositoryLocator.GetRepository(repoOptions.RepositoryType);
        }

        public IViewComponentResult SelectSitePartialView(int? SiteId = 0)
        {
            var Site = new Site();
            if (SiteId > 0)
                Site = repository.GetById((int)SiteId);

            if (Site != null)
            {
                ViewBag["CountryId"] = Country.GetCountrySelectList(countryRepository,Site.CountryId);
                ViewBag["CityId"] = City.GetCitySelectList(cityRepository, Site.CountryId, Site.CityId);
                ViewBag["SiteId"] = Site.GetCitySelectList(repository, Site.CountryId, Site.CityId, Site.Id);
            }
            else
            {
                ViewBag["CountryId"] = Country.GetCountrySelectList(countryRepository, 0);
                ViewBag["CityId"] = City.GetCitySelectList(cityRepository, 0,0);
                ViewBag["SiteId"] = Site.GetCitySelectList(repository, 0,0,0);
            }

            return View(Site) as IViewComponentResult;
        }

        // GET: SiteController
        public ActionResult Index()
        {
            List<Site> list = repository.GetAll().ToList();
            return View(list);
        }

        // GET: SiteController/Details/5
        public ActionResult Details(int id)
        {
            var model = repository.GetById(id);
            return View(model);
        }

        // GET: SiteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SiteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Site site)
        {
            try
            {
                repository.UpsertActivation(site);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(site);
            }
        }

        // GET: SiteController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = repository.GetById(id);
            ViewBag.Countries = ExtractSelectList(countryRepository.GetAll(), model.CountryId);
            ViewBag.Cities = ExtractSelectList(cityRepository.GetAll(), model.CityId);
            ViewBag.Sites = ExtractSelectList(repository.GetAll(), model.Id);

            return View(model);
        }


        // POST: SiteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Site site)
        {
            try
            {
                SiteFactory siteFactory = new SiteFactory(repoOptions);
                repository.Update(site);
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.Countries = ExtractSelectList(countryRepository.GetAll(), site.CountryId);
                ViewBag.Cities = ExtractSelectList(cityRepository.GetAll(), site.CityId);
                ViewBag.Sites = ExtractSelectList(repository.GetAll(), site.Id);

                return View(site);
            }
        }

        // GET: SiteController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = repository.GetById(id);
            repository.Delete(model);
            return RedirectToAction(nameof(Index));
        }


        private List<SelectListItem> ExtractSelectList(IEnumerable<IPersistentEntity> list, int selectValue)
        {
            var entities = list.OrderBy(x => x.Id).ToList();
            entities.Insert(0, new PersistentEntity() { Id = 0, Name = "--UnSelected--" });
            return entities
                .Select(x => new SelectListItem(x.Name, x.Id.ToString(), x.Id == selectValue)).ToList();
        }
    }
}

EDC2Reporting.WebAPI/Views/Home/AdminOnly.cshtml
This is an Admin only page

EDC2Reporting.WebAPI/Views/Home/DesignExperiment.cshtml
@{
    ViewData["Title"] = "Design my Experiment";
}

<div class="container">
    <h1>Design my Experiment</h1>

    <p class="lead">Quick links to design entities used in an experiment.</p>

    <div class="list-group">
        <a class="list-group-item list-group-item-action" asp-controller="VisitGroup" asp-action="Index">
            Manage Visit Groups
        </a>
        <a class="list-group-item list-group-item-action" asp-controller="Visit" asp-action="Index">
            Manage Visits
        </a>
        <a class="list-group-item list-group-item-action" asp-controller="Patients" asp-action="Index">
            Manage Patients
        </a>
        <a class="list-group-item list-group-item-action" asp-controller="CrfPages" asp-action="Index">
            Manage CRF Pages
        </a>
    </div>

    <hr />

    <p class="text-muted small mt-3">
        This action is only accessable for Clinical Trial Leaders (or System Administrators).
    </p>
</div>

EDC2Reporting.WebAPI/Views/Home/Index.cshtml
@using DataServices.SqlServerRepository.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Investigator> SignInManager
@inject UserManager<Investigator> UserManager
@inject SessionLayer.ISessionWrapper SessionWrapper
@inject DataServices.SqlServerRepository.EdcDbContext Db

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        <a asp-action="DesignExperiment" class="btn btn-outline-primary">Design Experiment</a>
    </p>
    <p>
        <a asp-controller="Investigator" asp-action="Index" class="btn btn-outline-primary">Manage Users</a>
    </p>
    <p>
        <a asp-controller="Site" asp-action="Index" class="btn btn-outline-primary">
            Manage Sites (Medical Research Centers)</a>
    </p>
    <p>
        <a asp-controller="Experiments" asp-action="Create" class="btn btn-outline-primary">New Experiment (Study)</a>
    </p>
</div>

@* Bottom status panel: shows logged-in user + session selection (patient / experiment / visit) *@
<div class="container mt-4">
    @if (SignInManager.IsSignedIn(User))
    {
        var investigator = await UserManager.GetUserAsync(User);

        var isAdmin = await UserManager.IsInRoleAsync(investigator, "Admin");
        var isLeader = await UserManager.IsInRoleAsync(investigator, "ClinicalTrialLeader");

        var patientId = SessionWrapper.SelectedPatientId;
        var visitId = SessionWrapper.SelectedVisitId;
        var visitIndex = SessionWrapper.SelectedVisitIndex;
        var visitGroupId = SessionWrapper.SelectedVisitGroupId;

        var patient = patientId > 0 ? await Db.Patients.FindAsync(patientId) : null;
        var visit = visitId > 0 ? await Db.Visits.FindAsync(visitId) : null;
        var visitGroup = visitGroupId > 0 ? await Db.VisitGroups.FindAsync(visitGroupId) : null;

        <div class="alert alert-secondary small">
            <div><strong>Currently logged in:</strong> @investigator.FirstName @investigator.LastName</div>
            <div><strong>Phone:</strong> @(string.IsNullOrWhiteSpace(investigator.PhoneNumber) ? "n/a" : investigator.PhoneNumber)
                 &nbsp;&nbsp;
                 <strong>Email:</strong> @(string.IsNullOrWhiteSpace(investigator.Email) ? "n/a" : investigator.Email)
            </div>

            <div class="mt-2">
                <strong>Selected patient:</strong>
                @{
                    if (patient != null)
                    {
                        <text>@($"{patient.Name} (Id: {patient.Id})")</text>;
                    }
                    else
                    {
                        <text>None selected</text>;
                        <text> &nbsp;</text>
                        <a asp-controller="Patients" asp-action="Select" class="btn btn-sm btn-primary">Select Patient</a>

                        if (isAdmin)
                        {
                            <span class="text-muted ms-2">(Admin can select any patient)</span>
                        }
                        else if (isLeader)
                        {
                            <span class="text-muted ms-2">(You can select patients in your assigned experiment)</span>
                        }
                        else
                        {
                            <span class="text-muted ms-2">(You can select patients for your experiment only)</span>
                        }
                    }
                }
            </div>

            <div class="mt-2">
                <strong>Selected experiment / visit group:</strong>
                @{
                    if (visitGroup != null)
                    {
                        <text>@visitGroup.Name</text>;
                    }
                    else
                    {
                        <text>None selected</text>;
                        <text> &nbsp;</text>
                        <a asp-controller="Experiments" asp-action="Select" class="btn btn-sm btn-secondary">Select Experiment</a>

                        if (isAdmin)
                        {
                            <span class="text-muted ms-2">(Admin can select any experiment)</span>
                        }
                        else if (isLeader)
                        {
                            <span class="text-muted ms-2">(You are limited to your assigned experiment)</span>
                        }
                        else
                        {
                            <span class="text-muted ms-2">(You can select experiments only if assigned)</span>
                        }
                    }
                }
            </div>

            <div class="mt-2">
                <strong>Visit number (index):</strong> @(visitIndex > 0 ? visitIndex.ToString() : "None selected")
                &nbsp;&nbsp;
                <strong>Visit id:</strong> @(visitId > 0 ? visitId.ToString() : "None selected")
                &nbsp;&nbsp;
                <strong>Visit name:</strong> @(visit != null ? visit.Name : "None selected")
            </div>
        </div>
    }
    else
    {
        <div class="alert alert-secondary small">No user signed in.</div>
    }
</div>